apiVersion: mogenius.com/v1alpha1
kind: PlatformDefault
spec:
  # renovate: datasource=helm registryUrl=https://grafana.github.io/helm-charts chart=alloy
  version: 1.8.2
  valuesObject:

    global:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
          
    configReloader:
      resources:
        requests:
          cpu: 15m
          memory: 40Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
