apiVersion: mogenius.com/v1alpha1
kind: PlatformDefault
spec:
  # renovate: datasource=helm registryUrl=https://argoproj.github.io/argo-helm chart=argo-cd
  version: 9.5.17
  valuesObject:
    releaseName: argocd
    valuesObject:
      crds:
        install: true
