apiVersion: mogenius.com/v1alpha1
kind: PlatformDefault
spec:
  # renovate: datasource=helm registryUrl=https://charts.external-secrets.io chart=external-secrets
  version: 2.6.0
  valuesObject:
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        cpu: 30m
        memory: 120Mi
      limits:
        memory: 300Mi
    log:
      level: warn
    webhook:
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      resources:
        requests:
          cpu: 10m
          memory: 80Mi
        limits:
          memory: 200Mi
    certController:
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      resources:
        requests:
          cpu: 10m
          memory: 80Mi
        limits:
          memory: 150Mi
