apiVersion: mogenius.com/v1alpha1
kind: PlatformDefault
spec:
  # renovate: datasource=helm registryUrl=https://prometheus-community.github.io/helm-charts chart=kube-prometheus-stack
  version: 85.3.0
  valuesObject: {}
